### ISSUE TITLE
tech/html/select jaws/chrome

### ISSUE THREAD

**Issue by smhigley** [accessibilitysupported/a11ysupport.io#106]
This Support Point submission is for the test [HTML select element test](/tests/tech__html__select)

I'd mark the select name test as a pass, since the name is conveyed as expected in scan mode. The behavior differences around whether the name is read when jumping by form field, using the elements list, or arrowing element by element matches how other form fields like text inputs are announced with JAWS. The "must convey an appropriate name" test is marked "pass" for the email input (https://a11ysupport.io/tests/tech__html__input__input-email), so it makes sense to me to pass it here too, since the behavior is the same.

meta info

| property | value |
| --- | --- |
| title | tech/html/select |
| at | jaws |
| at_version | 2019.1912.1 |
| browser | chrome |
| browser_version | 80 |
| os_version | 1909 |

select element: convey an appropriate name

| property | new value | old value |
| --- | --- | --- |
| feature_id | html/select_element | - |
| feature_assertion_id | convey_name | - |
| output_1_command | next_form_field | next_item |
| output_1_output | "Choose a food item, Combo box, apple" | "Combo box, apple" |
| output_1_result | pass | fail |
| output_1_notes | The label is read when jumping by form field or combobox and in the elements list, but is not repeated when moving item by item |  |

**Comment by smhigley** [comment]
I can also verify with JAWS 2020 in a bit, as soon as I manage to re-find the license instructions 😄

**Comment by mfairchild365** [comment]
Thank you @smhigley!

When using the down arrow command to navigate to the email input, I hear the label announced as I enter the actual input (after navigating past the actual label). However, when using the down arrow key to navigate to the select element in the same way, I don't hear the label. So, I think this should be marked as a failure to be consistent with other inputs. If you dive into the [details of the email test for JAWS+Chrome](https://a11ysupport.io/tests/tech__html__input__input-email#assertion-html-input(type-email)_element-convey_name-jaws-chrome), you can see many commands for the "must convey an appropriate name" assertion that pass, including `next_item`. 

I did notice that the select element is missing a command test for `next_form_field`. I can add these results to the test instead of replacing the `next_item` command.

Thoughts? Does that make sense? After updating to JAWS 2020, are you experiencing something different than I am?

**Comment by smhigley** [comment]
It looks like I don't have official access to 2020 yet 😢.

That said, I think I may have narrowed it down to something other than version number: JAWS does not read the label for me when I have a value in the text input, but it does read the label when the input is empty.

For what it's worth, I get the same sometimes-read-the-label-sometimes-don't results with NVDA and text and search inputs, and NVDA also does not read the label of `<select>` elements when using arrow keys in scan mode (and it also has the same behavior with checkboxes). I haven't tested much else, but I'm increasingly getting the feeling that reading label text when arrowing to a form field in scan mode is highly variable, and not necessarily an expected behavior across Windows screen readers.

Based on that, I think my own (personal, subjective) opinion is that this is a pass from JAWS, or a whole lot of other form fields need to be marked partial. Pass still makes more sense to me though :). I've never heard a JAWS user complain about this behavior or be confused by it, and I'm guessing anyone who hasn't been down this rabbit hole will be more confused than enlightened by a bunch "partial"s for such a core functionality of basic form controls.

**Comment by mfairchild365** [comment]
That’s fair and good feedback. It doesn’t match my experience testing across windows screen readers and inputs, but it certainly warrants further research. I wonder if the label being on the same line as the input affects results in NVDA. That might account for some of this.

Some options:

- remove all down arrow commands (just don’t test them)
- flag them programmatically so that they don’t contribute to the overall support for inputs. need to think more about how this would show up in the reporting and testing form. Flag could be something like: “not consistent” or “not expected to work”. Not sure yet on that. 

Either way, I’d like to do some more research on this. My gut says that the name not being announced for the down arrow command is not a big deal, unless (for some odd reason) the label is far away from the input in the DOM.

**Comment by mfairchild365** [comment]
I put together a [codepen to help with testing](https://codepen.io/mfairchild365/pen/zYGodew). Most screen readers announce the name when the label is on the same line (`display:inline`), but not when it is on another line (`display:block`).

I might update all `convey_name` assertions for inputs with a note that says:

> Commands to read line by line (down and up arrows in most windows screen readers) will not always result in the name being conveyed when the virtual focus is moved to an input. This is acceptable because the name should be naturally found in the reading order as the user is reading the page. Some screen readers choose to not convey the name in these cases, likely in an effort to reduce verbosity.

Then, mark them as passing with a note that the name is implied.

Thoughts? Does that work for you?

**Comment by mfairchild365** [comment]
Did some more testing and updated the codepen with results, which are copied here.

- NVDA 2019.3.1: label not announced when it is on a different line.
- JAWS 2020 and 2019: label is always announced
- Narrator 1909: label is always announced
- Orca 13.34: label is alwas announced
- VoiceOver (Mac): label is always announce

NVDA is the only outlier. And this was testing just a basic html text input, but I think that the text input is common enough to provide a solid baseline of expected functionality.

Since NVDA is the only screen reader with different behavior, I'm tempted to call this a bug. 

Curious what you think @smhigley

**Comment by smhigley** [comment]
Well that's weird 😅. I think the approach with the note sounds great!

Just to complicate things a bit further, my version + settings of JAWS (2019) does auto-switch into forms mode when entering a control, and the name is still sometimes not announced. That definitely happens when navigating to an input with focus (using arrow keys). Still trying to narrow down the other conditions; I wonder if there's something else going on and I need to reinstall either JAWS or Chrome 😂

**Comment by JAWS-test** [comment]
> my version + settings of JAWS (2019) does auto-switch into forms mode when entering a control, and the name is still sometimes not announced. That definitely happens when navigating to an input with focus (using arrow keys)

This is a long-standing JAWS bug that occurs in IE 11 and Chrome, but not in Firefox. The bug results from the auto-switch into forms mode for input fields. Mode switching can be disabled in the Settings Center. However, a test should be performed with the default settings (i.e. with mode switching).

**Comment by mfairchild365** [comment]
closing since this was addressed in https://github.com/accessibilitysupported/a11ysupport.io/commit/447cb614598ade4736e9644ac978e69e3e21c1f7

Please comment if you think that this is not fully addressed
