### ISSUE TITLE
aria-current on Chrome isn't supported

### ISSUE THREAD

**Issue by gurmukhp** [accessibilitysupported/a11ysupport.io#109]
The report shows that aria-current is supported, however it doesn't seem to be in Chrome v80 or v83 on Mac /Android (haven't tested Windows)

**Comment by mfairchild365** [comment]
Thank you for raising this issue @gurmukhp.

- Chrome + VoiceOver on MacOS is out of scope for our core listings because it is [reported to have 3% usage](https://webaim.org/projects/screenreadersurvey8/#browsercombos) and is not known to provide good support. As usage increases, we will start to include that in our core testing matrix.
- [Talkback + Chrome on Android is reported to not support `aria-current`](https://a11ysupport.io/tech/aria/aria-current_attribute), which matches your observations.

If there is something that I missed, please feel free to comment/re-open this issue.
