### ISSUE TITLE
indicate screen reader and browser versions

### ISSUE THREAD

**Issue by robfentress** [accessibilitysupported/a11ysupport.io#112]
This is _**such**_ a wonderful service you are providing, but I _really_ wish your matrices indicated the screen reader and browser versions, since support can vary greatly based on those.

**Comment by robfentress** [comment]
Nevermind.  I think I see [where that is listed](https://a11ysupport.io/tests/tech__html__select#history), but are there any places where you have tested more than one version and how do you handle those in the matrices?  I'm sorry, but I'm just returning to this after a while and am still trying to get a sense of how things are structured.

**Comment by mfairchild365** [comment]
Good question and I'm glad you like the project! As you found, versions are detailed under each test.

I've been wanting to display version numbers in support summaries, but have had trouble making that work. Reasons:

- Version numbers are log and detailed. I might be able to write a script to grab the major version number (JAWS 2020) for example instead of the whole string.
- Summary tables include aggregated testing information from many tests. Therefore, many versions might be tested. I could grab the min or max version. Do you think the min or max would be better? I'm leaning on the minimum.
- We only track a single version per AT/browser combination per test; we don't have a history beyond the summary found in the history section. Tracking a detailed history would have made the scope of the project too large for me to handle.
- Wiring all of this up would be a bit of a project, but doable.

**Comment by robfentress** [comment]
For **Summary of support by expectation and assistive technology**, what about a dynamically-filtered table that included all results, but that, by default, was filtered to only show the latest?  For instance, the table could have columns headers for JAWS 2018, JAWS 2019, JAWS 2020, and so forth.  Then, under each of those column headers, there could be column headers for Chrome 84, Chrome 83, Firefox 77, Firefox 76, and so on.  You could (maybe should) even include dot releases, but only include columns for AT and browsers you have actually tested.  This would only be necessary if you expect there might be significant differences--I haven't compared results between dot releases enough to know.  Above the table would be filters that let you choose the AT and browsers to be displayed.  The options available in the filters could be dynamically populated from the contents of the table.  The table could, of course, be huge and I don't know how performant the filtering would be, but, as an end user of the system, this is what I would find most useful.

**Comment by mfairchild365** [comment]
That is a good suggestion. When I designed this system, I assumed from personal experience as a developer that the most recent results would be more helpful than a detailed history of support by version. My goal was to provide informative and helpful information while keeping the system fairly easy to build, maintain, and use. Tracking detailed historical data was just too complex in terms of the data layer, maintenance, and display, and in my opinion, did not provide enough value to the target audience (devs and people curious about what 'supported' actually means).

In theory, detailed historical data will be available via the ARIA-AT project, so I'm not sure how valuable it would be to add here. I hope that the ARIA-AT project will eventually make this project obsolete.

**Comment by jordanrogers-iop** [comment]
Hey @mfairchild365, Jordan here! Happy to take a look at this.

**Comment by mfairchild365** [comment]
This was improved in https://github.com/accessibilitysupported/a11ysupport.io/pull/166
