### ISSUE TITLE
aria/application_role

### ISSUE THREAD

**Issue by Malvoz** [accessibilitysupported/a11ysupport.io#203]
https://a11ysupport.io/tech/aria/application_role

`role="application"` does not work as expected using Narrator on Windows 10 (no idea of where to find the version of Narrator I'm using) in Chrome v.96.0.4664.45.

Filed a bug: https://answers.microsoft.com/en-us/windows/forum/windows_11-wintop_apps-win_subtopwinapps/bug-narrator-ignores-aria-roleapplication/1252f6ff-ac41-4dd6-9b71-418b6eca40de (and in the Windows Feedback Hub: https://aka.ms/AAf1z86).

**Comment by scottaohara** [comment]
a few things here:
1. the application role is announced.  oddly you have it on a parent container rather than the element with role=region that is focused as its first child.  That seems unnecessary as in application mode the navigating by landmarks / other quick keys will be disabled anyway, so not sure what value there is for having a landmark within the application, instead of just focusing the application itself.
2. if i turn off scan mode, it works as you're expecting.  are you thinking that Narrator just automatically change to forms/application mode when navigating into or to an element with role=application (e.g., behave like jaws/nvda in their default mode)? That's not the default setting for narrator.  If you're in scan mode and navigate to a radio button, for example, it stays in scan mode.  You have to press `ins` + `space` to go into application/forms mode.

**Comment by Malvoz** [comment]
> Reviewing the markup it seemed odd that you have `role=appliation` on a parent container rather than the element with `role=region` that is focused as its first child.

Initially we were only using `role=region` on the focusable container, we're trying to make [pan and zoom meaningful to screen reader users](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/396) by [announcing movement](https://maps4html.org/experiments/screenreader/announce-pan-zoom/) (partial solution) so `role=application` is desirable, however simply replacing `region` with `application` on the focusable container resulted in "application" not being announced in NVDA which I thought was important to the user. That's perhaps a shadow DOM issue with NVDA? I'll revisit the roles and see if we can improve.

It certainly seems problematic to not have `<mapml-viewer>` wrapper be the focusable element, not sure we can do anything about that without breaking the wrapped LeafletJS component though.

> are you thinking that Narrator just automatically change to forms/application mode when navigating into or to an element with role=application (e.g., behave like jaws/nvda in their default mode)? That's not the default setting for narrator.

Yes, it didn't occur to me that Narrator could've just chosen to behave differently 😅, I'll withdraw my bug reports.
Thank you @scottaohara.
