### ISSUE TITLE
aria_hidden_text_input_custom nvda/firefox

### ISSUE THREAD

**Issue by ShadowBB** [accessibilitysupported/a11ysupport.io#5]
| property | value |
| --- | --- |
| title | aria_hidden_text_input_custom |
| support | y |
| at | nvda |
| at_version | 2018.2.1 |
| os_version | 17134.165 |
| browser | firefox |
| browser_version | 61.0.1 |

**Comment by mfairchild365** [comment]
Thank you, @ShadowBB - I leaning on requiring the commands+output that were used because that information will help future testers reproduce the results and understand how to use the assistive technology. 

Can you provide that information?

**Comment by mfairchild365** [comment]
I ran the same test with with a few different keyboard commands:

| property | value |
| --- | --- |
| title | aria_hidden_text_input_custom |
| support | p |
| at | nvda |
| at_version | 2018.2.1 |
| os_version | 1803 |
| browser | firefox |
| browser_version | 61.0.1 |
| output_1_command | down arrow |
| output_1_output | (target not read) |
| output_1_result | pass |
| output_2_command | tab |
| output_2_output | Your name edit has auto complete |
| output_2_result | pass |


When using focus mode (tab key) the control is still read. This is because the `aria-hidden="true"` does not make elements in the sub tree inert. It is the author's responsibility to make controls inert. See https://a11ysupport.io/tests/aria_hidden_text_input_custom for more information.
